export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// Import global styles (Tailwind + custom CSS)
import '../src/app/globals.css';

import Header from '../components/Header';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
